[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "nodejs_20", "composer"]

[phases.install]
cmds = ["npm install", "composer install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php -S 0.0.0.0:$PORT"